### ISSUE TITLE
terms and conditions 

### ISSUE THREAD

**Issue by net-gain-seo** [net-gain-seo/alpha-waste-child#1]
Move the following to the terms and conditions page - Minimum orders may apply. All orders are subject to approval. Prices exclude VAT. Delivery cost is included in UK mainland orders only.

Currently this is on each product page

**Comment by net-gain-seo** [comment]
**From Amanda**: Yes, we feel it should only be mentioned once on the website

**Comment by mitchtracy11** [comment]
The text has been removed from every product. And is now only located in the terms and conditions.
