### ISSUE TITLE
Wheeled Bins

### ISSUE THREAD

**Issue by net-gain-seo** [net-gain-seo/alpha-waste-child#6]
Can we have the wheeled bin liners on the same pages

**Comment by net-gain-seo** [comment]
Wheeled bin liners are for the 140L and 240L wheeled bins, can they please be put on the page for those bins

**Comment by net-gain-seo** [comment]
**From Amanda**: Under the paper sack category there are wheelie bin liners. 240L and 140L

**Comment by net-gain-seo** [comment]
see here: https://awsltduk.com/product/wheelie-bin-sack/ maybe add as a suggested product? do we have that built in?

**Comment by mitchtracy11** [comment]
All wheeled Bin will now cross reference the liners as well. For example: https://awsltduk.com/product/360l-two-wheeled-bins/
