### ISSUE TITLE
Waste Watcher

### ISSUE THREAD

**Issue by net-gain-seo** [net-gain-seo/alpha-waste-child#9]
Can you please add the lid option to the waste watcher

**Comment by net-gain-seo** [comment]
**From Amanda**

No, the price includes the lid.

Please remove the connector kit as we do not supply them.

Hope that makes it a bit easier!

**Comment by mitchtracy11** [comment]
Removed all the variations that were connected to "connector kit". Also added a lid option that has no price differences.
